[workspace]
members = [
    "wasm_tests",
    "yahtzee",
]

resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
strip = true
lto = true
